### ISSUE TITLE
Is possible to export each issue in a separated file?

### ISSUE THREAD

**Issue by guilhermeprokisch** [mattduck/gh2md#13]
I want to export each issue in a separated file. It's possible to do?

**Comment by mattduck** [comment]
That's not currently feature, but it wouldn't be a huge amount of work to implement. I'll try to get to it sometime, but realistically it's going to be at least a few weeks until I sit down to look at it.

**Comment by lhoupert** [comment]
Hi there! 
I would also be really interested in this possibility. I am using github issues as get-things-done lists :-) and it would be great to be able to easily export each individual issue as a md file. 
I got the idea after reading this nice article (https://rabernat.medium.com/advising-and-collaborating-during-a-pandemic-and-sabbatical-ca9531b82b6d).

**Comment by mattduck** [comment]
> it's going to be at least a few weeks until I sit down to look at it.

This was not a good estimate, my bad. Nearly a year late but I finally sat down and implemented multiple file support this morning.

Now if you pass the argument `--multiple-files`, your output path will be treated as a directory (instead of the default markdown file), and each issue/PR will be written to its own file, using the same formatting that it has when it's written to a single file. You can see an example of this at https://github.com/mattduck/gh2md/tree/master/examples/gh2md-multiple-files-example.

There is a new 1.0.1 release of gh2md that includes this feature. (It also removes support for user+password login as Github dropped supporting this a while back).

Hopefully this will be useful for somebody in the future. I'm going to close this as done but LMK if any feedback/issues.

**Comment by guilhermeprokisch** [comment]
Thanks, @mattduck!
